In [1]:
import numpy as np

In [2]:
from ann import Network

In [3]:
rede = Network(4)

In [4]:
rede.add_layer(5, "step")
rede.add_layer(3, "sigmoid")

In [5]:
rede.forward([1, 2, 3, 4])

array([0.53255697, 0.57647553, 0.75253318])

In [6]:
rede.print()

camada 1
weights [[ 0.71200146  0.58061334  0.96287072 -0.30001766  0.4905043 ]
 [-0.78131637  0.85371383  0.93124779  0.48328853  0.39892105]
 [-0.78967832  0.13153654  0.64950193  0.74324148  0.76355232]
 [ 0.1553386  -0.71405616 -0.66727785 -0.55078244 -0.57221661]]
biases [ 0.44901072 -0.95649548  0.36812645 -0.6180298  -0.28251006]
camada 2
weights [[ 0.88100539 -0.69359626 -0.0013148 ]
 [ 0.2235003   0.06298695  0.39394906]
 [ 0.60568621  0.69211399 -0.00476855]
 [-0.50504146 -0.35804325 -0.02584746]
 [ 0.34900383 -0.76624172  0.54765144]]
biases [-0.3192362   0.74049259  0.59513315]
