In [1]:
import numpy as np

In [2]:
from ann import Network

In [3]:
rede = Network(4)

In [4]:
rede.add_layer(5)
rede.add_layer(3)

In [5]:
rede.forward([1, 2, 3, 4])

array([6.32518143, 3.37144342, 3.53874156])

In [6]:
rede.print()

camada 1
weights [[ 0.86597723  0.24060651  0.2335654  -0.75647658  0.40348145]
 [ 0.27340379  0.59462405  0.60178116  0.93031387 -0.90882293]
 [-0.35479651 -0.39806135 -0.3554961  -0.29490785 -0.86535136]
 [-0.00783112 -0.94487382  0.32658997 -0.03974063 -0.15491624]]
biases [ 0.32564529 -0.8072021   0.12174761  0.75482174  0.09506155]
camada 2
weights [[ 0.04171644 -0.8653364   0.43439138]
 [-0.89577578 -0.67380474 -0.62032046]
 [ 0.19345059 -0.23782615  0.40156417]
 [ 0.99246272 -0.12648834  0.32171887]
 [-0.16905625 -0.50492667  0.03619669]]
biases [ 0.47707472 -0.76297262 -0.25993967]
